# base on latest python file
FROM python:latest

# add our python program
ADD prog.py ./

# install dependent libraries
RUN pip install numpy matplotlib

# the command to run our program
CMD [ "python", "./prog.py"]
